### PR TITLE
Hit 149 session notes

### PR DESCRIPTION
**Pull request by damienlaidinsonos**
Integrates taking notes in the OpenBCI interface. A session must have been started for this to work, the reason being the session folder name is generated when a session recording is triggered and I can't access it before. 

You can simulate a session by selecting `SYNTHETIC` as data source and then just start the session. I believe that just reads made up data from a file.

The `notes.txt` file will be saved in the session folder, in `/Users/<username>/Documents/OpenBCI_GUI/Recordings/<session_id>`

### CODE REVIEW

**Comment by damienlaidinsonos** [comment]
@conorsleithsonos Have you had a chance to test this ?

**Review by conorsleithsonos — CHANGES_REQUESTED** [review]
Still testing, but an initial thought:
The Notes button should be disabled while the Session Not Started dialog is alive -- otherwise, you can spawn arbitrarily many of these dialogs by spamming the Notes button.
image

**Comment by damienlaidinsonos** [comment]
Good idea, on it !

**Review by conorsleithsonos — APPROVED** [review]
I haven't been able to find any other way to break this. LGTM, nice work

**Pull request merged**
